coronatimes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),


]

main_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('blogposts/', views.blogposts_index, name='index'),
    path('blogposts/all/', views.blogposts_all, name='blogposts_all'),
    path('blogposts/create/', views.BlogpostCreate.as_view(),
         name='blogposts_create'),
    path('blogposts/<int:blogpost_id>/add_photo/',
         views.add_photo, name='add_photo'),
    path('blogposts/<int:blogpost_id>/', views.blogposts_detail, name='detail'),
    path('blogposts/<int:pk>/update/',
         views.BlogpostUpdate.as_view(), name='blogposts_update'),
    path('blogposts/<int:pk>/delete/',
         views.BlogpostDelete.as_view(), name='blogposts_delete'),
    path('blogposts/<int:blogpost_id>/add_comment/',
         views.add_comment, name='add_comment'),
    path('accounts/signup/', views.signup, name='signup'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Blogpost(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField(max_length=3000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'blogpost_id': self.id})

class Comment(models.Model):
    body = models.TextField(max_length=3000)
    blogpost = models.ForeignKey(Blogpost, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.body

class Photo(models.Model):
    url = models.CharField(max_length=200)
    blogpost = models.ForeignKey(Blogpost, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for blogpost_id: {self.blogpost_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['body']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from newsapi import NewsApiClient

import uuid
import boto3

from .models import Blogpost, Comment, Photo
from .forms import CommentForm
S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'catcollector-nn'


def home(request):
    newsapi = NewsApiClient(api_key='313c12fcfda3465f89f36b377c088e3b')
    top = newsapi.get_top_headlines(q='coronavirus',
                                    language='en')

    l = top['articles']
    desc = []
    news = []
    img = []

    for i in range(len(l)):
        f = l[i]
        news.append(f['title'])
        desc.append(f['description'])
        img.append(f['urlToImage'])
    mylist = zip(news, desc, img)

    return render(request, 'home.html', context={"mylist": mylist})


def about(request):
    return render(request, 'about.html')


def blogposts_index(request):
    blogposts = Blogpost.objects.filter(user=request.user)
    return render(request, 'blogposts/index.html', {'blogposts': blogposts})


def blogposts_all(request):
    blogposts = Blogpost.objects.all()
    return render(request, 'blogposts/get_all_posts.html', {'blogposts': blogposts})


def blogposts_detail(request, blogpost_id):
    blogpost = Blogpost.objects.get(id=blogpost_id)
    comment_form = CommentForm()
    return render(request, 'blogposts/detail.html', {'blogpost': blogpost, 'comment_form': comment_form})


def signup(request):
    error_message = ''

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def add_comment(request, blogpost_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.blogpost_id = blogpost_id
        new_comment.save()
    return redirect('detail', blogpost_id=blogpost_id)


@login_required
def add_photo(request, blogpost_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, blogpost_id=blogpost_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', blogpost_id=blogpost_id)


class BlogpostCreate(CreateView):
    model = Blogpost
    fields = ['title', 'body']
    success_url = '/blogposts/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BlogpostUpdate(UpdateView):
    model = Blogpost
    fields = ['title', 'body']


class BlogpostDelete(DeleteView):
    model = Blogpost
    success_url = '/blogposts/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About Corona Times</h1>
<p class="about">The purpose of this app is to provide users with up to date news on the current pandemic, Coronavirus.
    This app will
    also serve as a social media outlet for users to post their quarantine pics and blog about what is going on in their
    life during this time. Users can comment on each others posts and have a place to get their voice out there.</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Corona Times</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css2?family=IM+Fell+French+Canon+SC&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Eagle+Lake&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body id="frame">
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper" id="navbar">
                <ul>
                    <li><a href="/" class="logo">&nbsp;&nbsp;Corona Times</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'home' %}">News Feed</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'blogposts_create' %}">Add Blogpost</a></li>
                    <li><a href="{% url 'index' %}">Your Blogposts</a></li>
                    <li><a href="{% url 'blogposts_all' %}">All Blogposts</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    </div>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2020 Corona Times &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/blogposts/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{blogpost.title}}</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ blogpost.body }}</span>
        <p>Posted By: <blockquote>{{ blogpost.user }}</blockquote>
        </p>
      </div>
      <div class="card-action">
        <a href="{% url 'blogposts_update' blogpost.id %}">Edit</a>
        <a href="{% url 'blogposts_delete' blogpost.id %}">Delete</a </div>
      </div>
      {%for photo in blogpost.photo_set.all%}
      <img class="responsive-img card-panel" src="{{photo.url}}" />
      {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
      <form action="{% url 'add_photo' blogpost.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file" />
        <br /><br />
        <input type="submit" class="btn" value="Upload Photo" />
      </form>
      <div class="col s6">
        <form action="{% url 'add_comment' blogpost.id %}" method="post">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <input type="submit" class="btn" value="Add Comment">
        </form>
        <table class="striped">
          <thead>
            <tr>
              <th></th>
            </tr>
          </thead>
      </div>
      <tbody>
        {% for comment in blogpost.comment_set.all %}
        <tr>
          <div class="card">
            <p class="card-title">{{ comment.body }}</p>
          </div>
        </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
    {% endblock %}

main_app/templates/blogposts/get_all_posts.html
{% extends 'base.html' %}
{% block content %}

<h1>All Posts</h1>

{% for blogpost in blogposts %}
  <div class="card">
    <a href="{% url 'detail' blogpost.id %}">
    <div class="card-content">
      <span class="card-title">{{ blogpost.title }}</span>
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/blogposts/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Your Posts</h1>

{% for blogpost in blogposts %}
<div class="card">
  <a href="{% url 'detail' blogpost.id %}">
    <div class="card-content">
      <span class="card-title">{{ blogpost.title }}</span>
      <p>{{ blogpost.body }}</p>
    </div>
</div>
<a href="/password_change" style="color:#0d47a1;">Change Password</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} 
{% block content %}

<div class="container">
  <div class="card">
    <div>
      {% for new, des, i in mylist %}
      <div class="card-image">
        <img src="{{ i }}" alt="" />
      </div>
      <div class="card-title">{{ new }}</div>
      <p class="card-content">{{ des }}</p>
      <hr />
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Post</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn red">
    <a href="{% url 'detail' blogpost.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/blogpost_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Post New Blog Post</h1>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Post!" class="btn">
  </form>
{% endblock %}